In [53]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import r2_score

In [11]:
df = pd.read_csv('BostonHousing.csv')
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [12]:
df.shape

(506, 14)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   crim     506 non-null    float64
 1   zn       506 non-null    float64
 2   indus    506 non-null    float64
 3   chas     506 non-null    int64
 4   nox      506 non-null    float64
 5   rm       501 non-null    float64
 6   age      506 non-null    float64
 7   dis      506 non-null    float64
 8   rad      506 non-null    int64
 9   tax      506 non-null    int64
 10  ptratio  506 non-null    float64
 11  b        506 non-null    float64
 12  lstat    506 non-null    float64
 13  medv     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB

In [14]:
df.isna().sum()

crim       0
zn         0
indus      0
chas       0
nox        0
rm         5
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

In [15]:
rm_median = df['rm'].median()

In [16]:
df['rm'] = df['rm'].fillna(rm_median)

In [17]:
df.isna().sum()

crim       0
zn         0
indus      0
chas       0
nox        0
rm         0
age        0
dis        0
rad        0
tax        0
ptratio    0
b          0
lstat      0
medv       0
dtype: int64

In [18]:
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [26]:
x = df.iloc[:, 0:13]
y = df.iloc[:, -1]

In [27]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [28]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
std = StandardScaler()
x_scaled = std.fit_transform(x)

In [29]:
x_scaled

array([[-0.41978194,  0.28482986, -1.2879095 , ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, ..., -0.30309415,
         0.44105193, -0.49243937],
       [-0.41734159, -0.48772236, -0.59338101, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.98304761],
       [-0.40776407, -0.48772236,  0.11573841, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [-0.41500016, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.66905833]])

In [39]:
# Dataset Split
from sklearn.model_selection import train_test_split as tts
xtrain, xtest, ytrain, ytest = tts(x_scaled, y, test_size=0.2, random_state=42)

In [40]:
xtrain.shape

(404, 13)

In [41]:
xtest.shape

(102, 13)

In [42]:
ytest.shape

(102,)

In [43]:
ytrain.shape

(404,)

In [44]:
# Apply Linear Regression
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(xtrain, ytrain)

LinearRegression()

In [45]:
lr.score(xtrain, ytrain)

0.7506143967274728

In [46]:
lr.score(xtest, ytest)

0.6665030487253161

In [47]:
ypred = lr.predict(xtest)
ypred

array([28.98569055, 36.00706941, 14.84438855, 25.02061382, 18.77386209,
       23.26220973, 17.6698461 , 14.3512927 , 23.02076629, 20.62526059,
       24.91948199, 18.66813486, -6.08246257, 21.76741109, 19.23854195,
       26.18956521, 20.66161361,  5.80148502, 40.49123015, 17.61851042,
       27.22842262, 30.04981803, 11.3475005 , 24.14676372, 17.85996976,
       15.84151224, 22.78020868, 14.57840365, 22.44477547, 19.18900883,
       22.42609485, 25.20991744, 25.93635035, 17.69976563, 16.77713405,
       16.96421169, 31.2317762 , 20.12060928, 23.76612789, 24.62158601,
       13.93830377, 32.23403436, 42.66084543, 17.33140543, 27.26044028,
       16.99500643, 14.07051828, 25.89261304, 20.30167196, 29.94677248,
       21.3125114 , 34.33708037, 16.04936489, 26.21092456, 39.5247777 ,
       22.58090068, 18.84854949, 32.70596651, 25.05791007, 12.90965247,
       20.2305824 , 30.48462009, 31.4999042 , 15.88082103, 20.2459958 ,
       16.72434534, 20.52551387, 25.95161425, 30.59728637, 11.59768631,
       20.50734804, 27.48344277, 11.02256124, 15.68959185, 23.79233879,
        6.20577891, 21.59338031, 41.40285541, 18.76815235,  8.90798665,
       20.83152012, 13.25971015, 20.75670884,  9.36976436, 23.22208283,
       31.90583027, 19.10545359, 25.50317223, 29.03222995, 20.15165287,
       25.57124797,  5.70037121, 20.10416343, 14.96789765, 12.49295161,
       20.73547705, 24.73321148, -0.16008296, 13.68196813, 16.18221115,
       22.26502404, 24.48019192])

In [55]:
# Model Evaluation
r2_score(ytest, ypred)

0.6665030487253161

In [70]:
# Apply Lasso Regression
from sklearn.linear_model import Lasso
ls = Lasso(alpha=0.1)

In [71]:
ls.fit(xtrain, ytrain)

Lasso(alpha=0.1)

In [72]:
ls.score(xtrain, ytrain)

0.7447194853029862

In [73]:
ls.score(xtest, ytest)

0.6472594441868946

In [74]:
ls_pred = ls.predict(xtest)
ls_pred

array([28.61448643, 34.62181726, 17.6075683 , 24.88135199, 18.58555064,
       23.73132469, 17.9831847 , 15.03401737, 22.34587367, 20.96205434,
       24.11096526, 19.4176244 , -5.25766315, 22.4452208 , 19.36856826,
       25.6556095 , 19.20165709,  5.38763912, 39.15440167, 17.53381804,
       26.25961923, 28.70696277, 12.08120832, 24.39169654, 17.60258796,
       15.17614192, 23.08381547, 15.07934257, 22.23828105, 19.57519617,
       21.91530406, 25.25645818, 25.86251519, 17.43070308, 16.16790351,
       17.91981437, 31.60306049, 19.94990164, 23.52200989, 24.52751134,
       14.24071346, 30.45246948, 40.50696753, 18.00732714, 27.30410856,
       16.56491274, 14.63701259, 25.82112463, 19.74652122, 30.51403825,
       21.89026926, 33.33596063, 16.7106224 , 26.78950786, 38.61674462,
       22.20472702, 18.66838447, 30.94183457, 25.07105933, 13.58173661,
       20.34766862, 29.58898711, 30.53958173, 16.10653524, 22.49108501,
       16.46416505, 20.20396666, 25.63644513, 29.29007976, 11.79654982,
       20.18712921, 26.94310144, 11.11709732, 16.84389215, 24.05956569,
        6.56659509, 22.02054952, 39.22279847, 18.52906012, 11.58226536,
       21.53125707, 12.36593934, 21.26539076,  8.91298661, 23.14789042,
       31.32395291, 19.1956124 , 25.54500142, 27.55199928, 20.98319108,
       25.24521585,  5.86442149, 21.08368202, 17.06395088, 11.51036988,
       21.7367196 , 23.96081486, -0.50844144, 14.17917162, 16.02230937,
       22.06688761, 24.92475744])

In [75]:
r2_score(ytest, ls_pred)

0.6472594441868946

In [76]:
import numpy as np
ls = Lasso()
para = {'alpha' : np.logspace(-1, 10, 1000)}
para

{'alpha': array([1.00000000e-01, 1.02567793e-01, 1.05201522e-01, 1.07902879e-01,
        1.10673602e-01, 1.13515471e-01, 1.16430313e-01, 1.19420003e-01,
        1.22486461e-01, 1.25631660e-01, 1.28857621e-01, 1.32166418e-01,
        1.35560179e-01, 1.39041083e-01, 1.42611371e-01, 1.46273336e-01,
        1.50029332e-01, 1.53881775e-01, 1.57833141e-01, 1.61885969e-01,
        1.66042866e-01, 1.70306503e-01, 1.74679622e-01, 1.79165033e-01,
        1.83765620e-01, 1.88484341e-01, 1.93324229e-01, 1.98288395e-01,
        2.03380031e-01, 2.08602409e-01, 2.13958887e-01, 2.19452909e-01,
        2.25088005e-01, 2.30867799e-01, 2.36796007e-01, 2.42876438e-01,
        2.49113003e-01, 2.55509709e-01, 2.62070670e-01, 2.68800102e-01,
        2.75702333e-01, 2.82781798e-01, 2.90043049e-01, 2.97490755e-01,
        3.05129702e-01, 3.12964801e-01, 3.21001090e-01, 3.29243733e-01,
        3.37698031e-01, 3.46369418e-01, 3.55263468e-01, 3.64385898e-01,
        3.73742574e-01, 3.83339510e-01, 3.93182876e-01, 4.03278998e-01,
        4.13634368e-01, 4.24255643e-01, 4.35149650e-01, 4.46323393e-01,
        4.57784054e-01, 4.69539001e-01, 4.81595791e-01, 4.93962174e-01,
        5.06646101e-01, 5.19655724e-01, 5.32999408e-01, 5.46685730e-01,
        5.60723488e-01, 5.75121707e-01, 5.89889643e-01, 6.05036788e-01,
        6.20572881e-01, 6.36507908e-01, 6.52852114e-01, 6.69616005e-01,
        6.86810359e-01, 7.04446228e-01, 7.22534949e-01, 7.41088152e-01,
        7.60117762e-01, 7.79636013e-01, 7.99655453e-01, 8.20188950e-01,
        8.41249705e-01, 8.62851257e-01, 8.85007491e-01, 9.07732653e-01,
        9.31041349e-01, 9.54948564e-01, 9.79469667e-01, 1.00462042e+00,
        1.03041699e+00, 1.05687597e+00, 1.08401436e+00, 1.11184960e+00,
        1.14039960e+00, 1.16968270e+00, 1.19971774e+00, 1.23052400e+00,
        1.26212131e+00, 1.29452998e+00, 1.32777083e+00, 1.36186524e+00,
        1.39683512e+00, 1.43270295e+00, 1.46949180e+00, 1.50722531e+00,
        1.54592774e+00, 1.58562396e+00, 1.62633950e+00, 1.66810054e+00,
        1.71093391e+00, 1.75486715e+00, 1.79992851e+00, 1.84614695e+00,
        1.89355218e+00, 1.94217468e+00, 1.99204571e+00, 2.04319732e+00,
        2.09566240e+00, 2.14947467e+00, 2.20466874e+00, 2.26128007e+00,
        2.31934506e+00, 2.37890104e+00, 2.43998630e+00, 2.50264010e+00,
        2.56690272e+00, 2.63281547e+00, 2.70042072e+00, 2.76976194e+00,
        2.84088369e+00, 2.91383170e+00, 2.98865287e+00, 3.06539530e+00,
        3.14410830e+00, 3.22484250e+00, 3.30764978e+00, 3.39258338e+00,
        3.47969790e+00, 3.56904935e+00, 3.66069515e+00, 3.75469422e+00,
        3.85110700e+00, 3.94999546e+00, 4.05142317e+00, 4.15545533e+00,
        4.26215883e+00, 4.37160225e+00, 4.48385595e+00, 4.59899209e+00,
        4.71708469e+00, 4.83820966e+00, 4.96244488e+00, 5.08987019e+00,
        5.22056753e+00, 5.35462090e+00, 5.49211648e+00, 5.63314267e+00,
        5.77779012e+00, 5.92615181e+00, 6.07832313e+00, 6.23440189e+00,
        6.39448843e+00, 6.55868566e+00, 6.72709914e+00, 6.89983712e+00,
        7.07701066e+00, 7.25873365e+00, 7.44512291e+00, 7.63629826e+00,
        7.83238260e+00, 8.03350198e+00, 8.23978568e+00, 8.45136633e+00,
        8.66837993e+00, 8.89096599e+00, 9.11926760e+00, 9.35343152e+00,
        9.59360829e+00, 9.83995230e+00, 1.00926219e+01, 1.03517796e+01,
        1.06175918e+01, 1.08902296e+01, 1.11698682e+01, 1.14566873e+01,
        1.17508713e+01, 1.20526094e+01, 1.23620954e+01, 1.26795285e+01,
        1.30051125e+01, 1.33390569e+01, 1.36815763e+01, 1.40328908e+01,
        1.43932264e+01, 1.47628147e+01, 1.51418933e+01, 1.55307057e+01,
        1.59295021e+01, 1.63385388e+01, 1.67580786e+01, 1.71883914e+01,
        1.76297538e+01, 1.80824493e+01, 1.85467692e+01, 1.90230119e+01,
        1.95114835e+01, 2.00124980e+01, 2.05263775e+01, 2.10534524e+01,
        2.15940615e+01, 2.21485523e+01, 2.27172813e+01, 2.33006141e+01,
        2.38989257e+01, 2.45126006e+01, 2.51420335e+01, 2.57876289e+01,
        2.64498018e+01, 2.71289780e+01, 2.78255940e+01, 2.85400977e+01,
        2.92729484e+01, 3.00246171e+01, 3.07955871e+01, 3.15863541e+01,
        3.23974263e+01, 3.32293252e+01, 3.40825855e+01, 3.49577557e+01,
        3.58553986e+01, 3.67760910e+01, 3.77204249e+01, 3.86890074e+01,
        3.96824610e+01, 4.07014245e+01, 4.17465529e+01, 4.28185180e+01,
        4.39180089e+01, 4.50457325e+01, 4.62024137e+01, 4.73887961e+01,
        4.86056423e+01, 4.98537346e+01, 5.11338754e+01, 5.24468875e+01,
        5.37936150e+01, 5.51749238e+01, 5.65917016e+01, 5.80448594e+01,
        5.95353313e+01, 6.10640754e+01, 6.26320745e+01, 6.42403366e+01,
        6.58898955e+01, 6.75818117e+01, 6.93171728e+01, 7.10970943e+01,
        7.29227206e+01, 7.47952252e+01, 7.67158118e+01, 7.86857151e+01,
        8.07062014e+01, 8.27785697e+01, 8.49041520e+01, 8.70843150e+01,
        8.93204600e+01, 9.16140246e+01, 9.39664831e+01, 9.63793480e+01,
        9.88541702e+01, 1.01392541e+02, 1.03996091e+02, 1.06666496e+02,
        1.09405471e+02, 1.12214777e+02, 1.15096220e+02, 1.18051653e+02,
        1.21082975e+02, 1.24192135e+02, 1.27381132e+02, 1.30652016e+02,
        1.34006890e+02, 1.37447909e+02, 1.40977287e+02, 1.44597292e+02,
        1.48310251e+02, 1.52118552e+02, 1.56024641e+02, 1.60031031e+02,
        1.64140297e+02, 1.68355080e+02, 1.72678090e+02, 1.77112106e+02,
        1.81659979e+02, 1.86324631e+02, 1.91109062e+02, 1.96016347e+02,
        2.01049642e+02, 2.06212180e+02, 2.11507282e+02, 2.16938352e+02,
        2.22508880e+02, 2.28222447e+02, 2.34082728e+02, 2.40093488e+02,
        2.46258592e+02, 2.52582003e+02, 2.59067786e+02, 2.65720111e+02,
        2.72543253e+02, 2.79541600e+02, 2.86719650e+02, 2.94082017e+02,
        3.01633435e+02, 3.09378757e+02, 3.17322963e+02, 3.25471161e+02,
        3.33828586e+02, 3.42400614e+02, 3.51192753e+02, 3.60210656e+02,
        3.69460121e+02, 3.78947092e+02, 3.88677669e+02, 3.98658107e+02,
        4.08894823e+02, 4.19394396e+02, 4.30163576e+02, 4.41209286e+02,
        4.52538628e+02, 4.64158883e+02, 4.76077523e+02, 4.88302209e+02,
        5.00840799e+02, 5.13701354e+02, 5.26892142e+02, 5.40421642e+02,
        5.54298552e+02, 5.68531791e+02, 5.83130511e+02, 5.98104096e+02,
        6.13462172e+02, 6.29214611e+02, 6.45371540e+02, 6.61943346e+02,
        6.78940681e+02, 6.96374473e+02, 7.14255929e+02, 7.32596543e+02,
        7.51408106e+02, 7.70702711e+02, 7.90492762e+02, 8.10790981e+02,
        8.31610415e+02, 8.52964450e+02, 8.74866812e+02, 8.97331581e+02,
        9.20373200e+02, 9.44006479e+02, 9.68246612e+02, 9.93109181e+02,
        1.01861017e+03, 1.04476597e+03, 1.07159340e+03, 1.09910970e+03,
        1.12733256e+03, 1.15628013e+03, 1.18597101e+03, 1.21642429e+03,
        1.24765955e+03, 1.27969687e+03, 1.31255684e+03, 1.34626058e+03,
        1.38082977e+03, 1.41628662e+03, 1.45265393e+03, 1.48995507e+03,
        1.52821404e+03, 1.56745541e+03, 1.60770442e+03, 1.64898694e+03,
        1.69132952e+03, 1.73475936e+03, 1.77930439e+03, 1.82499324e+03,
        1.87185529e+03, 1.91992067e+03, 1.96922026e+03, 2.01978576e+03,
        2.07164968e+03, 2.12484535e+03, 2.17940698e+03, 2.23536965e+03,
        2.29276931e+03, 2.35164288e+03, 2.41202821e+03, 2.47396410e+03,
        2.53749038e+03, 2.60264788e+03, 2.66947849e+03, 2.73802518e+03,
        2.80833200e+03, 2.88044415e+03, 2.95440800e+03, 3.03027108e+03,
        3.10808217e+03, 3.18789129e+03, 3.26974974e+03, 3.35371015e+03,
        3.43982649e+03, 3.52815412e+03, 3.61874981e+03, 3.71167182e+03,
        3.80697987e+03, 3.90473524e+03, 4.00500076e+03, 4.10784089e+03,
        4.21332174e+03, 4.32151113e+03, 4.43247859e+03, 4.54629547e+03,
        4.66303493e+03, 4.78277202e+03, 4.90558371e+03, 5.03154895e+03,
        5.16074871e+03, 5.29326606e+03, 5.42918618e+03, 5.56859644e+03,
        5.71158648e+03, 5.85824820e+03, 6.00867589e+03, 6.16296626e+03,
        6.32121848e+03, 6.48353429e+03, 6.65001803e+03, 6.82077673e+03,
        6.99592017e+03, 7.17556092e+03, 7.35981448e+03, 7.54879928e+03,
        7.74263683e+03, 7.94145172e+03, 8.14537177e+03, 8.35452806e+03,
        8.56905505e+03, 8.78909065e+03, 9.01477631e+03, 9.24625712e+03,
        9.48368187e+03, 9.72720319e+03, 9.97697764e+03, 1.02331658e+04,
        1.04959323e+04, 1.07654461e+04, 1.10418805e+04, 1.13254132e+04,
        1.16162263e+04, 1.19145070e+04, 1.22204469e+04, 1.25342427e+04,
        1.28560961e+04, 1.31862140e+04, 1.35248087e+04, 1.38720978e+04,
        1.42283046e+04, 1.45936580e+04, 1.49683929e+04, 1.53527503e+04,
        1.57469771e+04, 1.61513269e+04, 1.65660596e+04, 1.69914417e+04,
        1.74277468e+04, 1.78752553e+04, 1.83342548e+04, 1.88050406e+04,
        1.92879151e+04, 1.97831888e+04, 2.02911802e+04, 2.08122157e+04,
        2.13466303e+04, 2.18947676e+04, 2.24569800e+04, 2.30336287e+04,
        2.36250847e+04, 2.42317279e+04, 2.48539486e+04, 2.54921465e+04,
        2.61467321e+04, 2.68181261e+04, 2.75067601e+04, 2.82130768e+04,
        2.89375302e+04, 2.96805861e+04, 3.04427221e+04, 3.12244282e+04,
        3.20262069e+04, 3.28485737e+04, 3.36920571e+04, 3.45571994e+04,
        3.54445567e+04, 3.63546996e+04, 3.72882131e+04, 3.82456972e+04,
        3.92277676e+04, 4.02350555e+04, 4.12682085e+04, 4.23278907e+04,
        4.34147833e+04, 4.45295851e+04, 4.56730127e+04, 4.68458012e+04,
        4.80487044e+04, 4.92824957e+04, 5.05479682e+04, 5.18459354e+04,
        5.31772318e+04, 5.45427131e+04, 5.59432571e+04, 5.73797641e+04,
        5.88531578e+04, 6.03643851e+04, 6.19144176e+04, 6.35042517e+04,
        6.51349095e+04, 6.68074392e+04, 6.85229160e+04, 7.02824426e+04,
        7.20871503e+04, 7.39381992e+04, 7.58367791e+04, 7.77841107e+04,
        7.97814457e+04, 8.18300682e+04, 8.39312950e+04, 8.60864770e+04,
        8.82969996e+04, 9.05642838e+04, 9.28897872e+04, 9.52750047e+04,
        9.77214697e+04, 1.00230755e+05, 1.02804473e+05, 1.05444279e+05,
        1.08151870e+05, 1.10928986e+05, 1.13777413e+05, 1.16698982e+05,
        1.19695570e+05, 1.22769105e+05, 1.25921561e+05, 1.29154967e+05,
        1.32471399e+05, 1.35872990e+05, 1.39361927e+05, 1.42940453e+05,
        1.46610868e+05, 1.50375532e+05, 1.54236865e+05, 1.58197348e+05,
        1.62259529e+05, 1.66426018e+05, 1.70699493e+05, 1.75082703e+05,
        1.79578465e+05, 1.84189668e+05, 1.88919278e+05, 1.93770334e+05,
        1.98745955e+05, 2.03849340e+05, 2.09083769e+05, 2.14452608e+05,
        2.19959307e+05, 2.25607407e+05, 2.31400538e+05, 2.37342425e+05,
        2.43436887e+05, 2.49687843e+05, 2.56099310e+05, 2.62675410e+05,
        2.69420371e+05, 2.76338529e+05, 2.83434331e+05, 2.90712338e+05,
        2.98177229e+05, 3.05833803e+05, 3.13686982e+05, 3.21741815e+05,
        3.30003479e+05, 3.38477286e+05, 3.47168682e+05, 3.56083255e+05,
        3.65226736e+05, 3.74605003e+05, 3.84224085e+05, 3.94090164e+05,
        4.04209584e+05, 4.14588850e+05, 4.25234633e+05, 4.36153779e+05,
        4.47353305e+05, 4.58840413e+05, 4.70622485e+05, 4.82707097e+05,
        4.95102016e+05, 5.07815211e+05, 5.20854855e+05, 5.34229330e+05,
        5.47947234e+05, 5.62017385e+05, 5.76448828e+05, 5.91250841e+05,
        6.06432940e+05, 6.22004883e+05, 6.37976681e+05, 6.54358602e+05,
        6.71161177e+05, 6.88395207e+05, 7.06071771e+05, 7.24202233e+05,
        7.42798248e+05, 7.61871770e+05, 7.81435061e+05, 8.01500696e+05,
        8.22081576e+05, 8.43190929e+05, 8.64842328e+05, 8.87049689e+05,
        9.09827289e+05, 9.33189772e+05, 9.57152154e+05, 9.81729841e+05,
        1.00693863e+06, 1.03279473e+06, 1.05931476e+06, 1.08651577e+06,
        1.11441525e+06, 1.14303113e+06, 1.17238180e+06, 1.20248614e+06,
        1.23336350e+06, 1.26503372e+06, 1.29751717e+06, 1.33083472e+06,
        1.36500781e+06, 1.40005838e+06, 1.43600898e+06, 1.47288272e+06,
        1.51070330e+06, 1.54949504e+06, 1.58928287e+06, 1.63009236e+06,
        1.67194976e+06, 1.71488197e+06, 1.75891659e+06, 1.80408193e+06,
        1.85040702e+06, 1.89792164e+06, 1.94665634e+06, 1.99664245e+06,
        2.04791210e+06, 2.10049824e+06, 2.15443469e+06, 2.20975611e+06,
        2.26649808e+06, 2.32469706e+06, 2.38439047e+06, 2.44561668e+06,
        2.50841506e+06, 2.57282597e+06, 2.63889081e+06, 2.70665207e+06,
        2.77615329e+06, 2.84743917e+06, 2.92055551e+06, 2.99554933e+06,
        3.07246884e+06, 3.15136348e+06, 3.23228398e+06, 3.31528234e+06,
        3.40041193e+06, 3.48772747e+06, 3.57728510e+06, 3.66914238e+06,
        3.76335836e+06, 3.85999362e+06, 3.95911027e+06, 4.06077203e+06,
        4.16504425e+06, 4.27199397e+06, 4.38168993e+06, 4.49420266e+06,
        4.60960449e+06, 4.72796959e+06, 4.84937407e+06, 4.97389596e+06,
        5.10161531e+06, 5.23261424e+06, 5.36697695e+06, 5.50478981e+06,
        5.64614142e+06, 5.79112265e+06, 5.93982669e+06, 6.09234915e+06,
        6.24878807e+06, 6.40924402e+06, 6.57382014e+06, 6.74262224e+06,
        6.91575883e+06, 7.09334120e+06, 7.27548353e+06, 7.46230289e+06,
        7.65391939e+06, 7.85045620e+06, 8.05203967e+06, 8.25879939e+06,
        8.47086827e+06, 8.68838264e+06, 8.91148232e+06, 9.14031075e+06,
        9.37501502e+06, 9.61574600e+06, 9.86265846e+06, 1.01159111e+07,
        1.03756668e+07, 1.06420924e+07, 1.09153594e+07, 1.11956432e+07,
        1.14831241e+07, 1.17779870e+07, 1.20804213e+07, 1.23906216e+07,
        1.27087871e+07, 1.30351224e+07, 1.33698374e+07, 1.37131472e+07,
        1.40652724e+07, 1.44264395e+07, 1.47968806e+07, 1.51768339e+07,
        1.55665436e+07, 1.59662602e+07, 1.63762407e+07, 1.67967487e+07,
        1.72280545e+07, 1.76704353e+07, 1.81241755e+07, 1.85895668e+07,
        1.90669084e+07, 1.95565072e+07, 2.00586778e+07, 2.05737431e+07,
        2.11020343e+07, 2.16438909e+07, 2.21996612e+07, 2.27697026e+07,
        2.33543814e+07, 2.39540736e+07, 2.45691646e+07, 2.52000499e+07,
        2.58471351e+07, 2.65108360e+07, 2.71915794e+07, 2.78898029e+07,
        2.86059554e+07, 2.93404971e+07, 3.00939003e+07, 3.08666494e+07,
        3.16592411e+07, 3.24721849e+07, 3.33060034e+07, 3.41612327e+07,
        3.50384225e+07, 3.59381366e+07, 3.68609536e+07, 3.78074666e+07,
        3.87782841e+07, 3.97740302e+07, 4.07953450e+07, 4.18428851e+07,
        4.29173238e+07, 4.40193519e+07, 4.51496777e+07, 4.63090280e+07,
        4.74981480e+07, 4.87178022e+07, 4.99687745e+07, 5.12518693e+07,
        5.25679112e+07, 5.39177464e+07, 5.53022426e+07, 5.67222897e+07,
        5.81788007e+07, 5.96727120e+07, 6.12049837e+07, 6.27766011e+07,
        6.43885743e+07, 6.60419396e+07, 6.77377600e+07, 6.94771255e+07,
        7.12611543e+07, 7.30909933e+07, 7.49678187e+07, 7.68928372e+07,
        7.88672862e+07, 8.08924349e+07, 8.29695852e+07, 8.51000725e+07,
        8.72852662e+07, 8.95265713e+07, 9.18254284e+07, 9.41833153e+07,
        9.66017480e+07, 9.90822810e+07, 1.01626509e+08, 1.04236067e+08,
        1.06912634e+08, 1.09657929e+08, 1.12473718e+08, 1.15361810e+08,
        1.18324063e+08, 1.21362380e+08, 1.24478715e+08, 1.27675070e+08,
        1.30953502e+08, 1.34316117e+08, 1.37765077e+08, 1.41302599e+08,
        1.44930957e+08, 1.48652484e+08, 1.52469573e+08, 1.56384676e+08,
        1.60400311e+08, 1.64519059e+08, 1.68743568e+08, 1.73076553e+08,
        1.77520801e+08, 1.82079168e+08, 1.86754584e+08, 1.91550056e+08,
        1.96468665e+08, 2.01513573e+08, 2.06688025e+08, 2.11995346e+08,
        2.17438948e+08, 2.23022330e+08, 2.28749082e+08, 2.34622885e+08,
        2.40647515e+08, 2.46826845e+08, 2.53164848e+08, 2.59665597e+08,
        2.66333273e+08, 2.73172160e+08, 2.80186656e+08, 2.87381269e+08,
        2.94760626e+08, 3.02329468e+08, 3.10092664e+08, 3.18055202e+08,
        3.26222201e+08, 3.34598912e+08, 3.43190720e+08, 3.52003147e+08,
        3.61041860e+08, 3.70312668e+08, 3.79821531e+08, 3.89574562e+08,
        3.99578030e+08, 4.09838367e+08, 4.20362168e+08, 4.31156199e+08,
        4.42227398e+08, 4.53582883e+08, 4.65229952e+08, 4.77176095e+08,
        4.89428990e+08, 5.01996513e+08, 5.14886745e+08, 5.28107971e+08,
        5.41668691e+08, 5.55577622e+08, 5.69843706e+08, 5.84476113e+08,
        5.99484250e+08, 6.14877765e+08, 6.30666554e+08, 6.46860766e+08,
        6.63470812e+08, 6.80507370e+08, 6.97981391e+08, 7.15904109e+08,
        7.34287045e+08, 7.53142017e+08, 7.72481145e+08, 7.92316862e+08,
        8.12661920e+08, 8.33529397e+08, 8.54932707e+08, 8.76885609e+08,
        8.99402217e+08, 9.22497005e+08, 9.46184819e+08, 9.70480888e+08,
        9.95400829e+08, 1.02096066e+09, 1.04717682e+09, 1.07406615e+09,
        1.10164595e+09, 1.12993394e+09, 1.15894830e+09, 1.18870770e+09,
        1.21923125e+09, 1.25053859e+09, 1.28264983e+09, 1.31558562e+09,
        1.34936714e+09, 1.38401610e+09, 1.41955477e+09, 1.45600600e+09,
        1.49339322e+09, 1.53174046e+09, 1.57107239e+09, 1.61141428e+09,
        1.65279206e+09, 1.69523234e+09, 1.73876240e+09, 1.78341022e+09,
        1.82920450e+09, 1.87617469e+09, 1.92435098e+09, 1.97376433e+09,
        2.02444651e+09, 2.07643011e+09, 2.12974854e+09, 2.18443607e+09,
        2.24052787e+09, 2.29805999e+09, 2.35706941e+09, 2.41759408e+09,
        2.47967289e+09, 2.54334576e+09, 2.60865362e+09, 2.67563844e+09,
        2.74434330e+09, 2.81481236e+09, 2.88709092e+09, 2.96122544e+09,
        3.03726358e+09, 3.11525422e+09, 3.19524751e+09, 3.27729485e+09,
        3.36144900e+09, 3.44776405e+09, 3.53629550e+09, 3.62710025e+09,
        3.72023668e+09, 3.81576466e+09, 3.91374560e+09, 4.01424249e+09,
        4.11731993e+09, 4.22304419e+09, 4.33148322e+09, 4.44270675e+09,
        4.55678627e+09, 4.67379511e+09, 4.79380850e+09, 4.91690358e+09,
        5.04315949e+09, 5.17265739e+09, 5.30548053e+09, 5.44171429e+09,
        5.58144625e+09, 5.72476624e+09, 5.87176639e+09, 6.02254120e+09,
        6.17718760e+09, 6.33580499e+09, 6.49849535e+09, 6.66536327e+09,
        6.83651600e+09, 7.01206359e+09, 7.19211887e+09, 7.37679760e+09,
        7.56621850e+09, 7.76050334e+09, 7.95977700e+09, 8.16416760e+09,
        8.37380654e+09, 8.58882856e+09, 8.80937190e+09, 9.03557835e+09,
        9.26759330e+09, 9.50556592e+09, 9.74964918e+09, 1.00000000e+10])}

In [77]:
# GridSearchCV
from sklearn.model_selection import GridSearchCV
gsc = GridSearchCV (ls, para, cv = 8, scoring="neg_mean_absolute_error")
gsc.fit(xtrain, ytrain)

GridSearchCV(cv=8, estimator=Lasso(),
             param_grid={'alpha': array([1.00000000e-01, 1.02567793e-01, 1.05201522e-01, 1.07902879e-01,
       1.10673602e-01, 1.13515471e-01, 1.16430313e-01, 1.19420003e-01,
       1.22486461e-01, 1.25631660e-01, 1.28857621e-01, 1.32166418e-01,
       1.35560179e-01, 1.39041083e-01, 1.42611371e-01, 1.46273336e-01,
       1.50029332e-01, 1.53881775e-01, 1.57833141e-01, 1....
       5.58144625e+09, 5.72476624e+09, 5.87176639e+09, 6.02254120e+09,
       6.17718760e+09, 6.33580499e+09, 6.49849535e+09, 6.66536327e+09,
       6.83651600e+09, 7.01206359e+09, 7.19211887e+09, 7.37679760e+09,
       7.56621850e+09, 7.76050334e+09, 7.95977700e+09, 8.16416760e+09,
       8.37380654e+09, 8.58882856e+09, 8.80937190e+09, 9.03557835e+09,
       9.26759330e+09, 9.50556592e+09, 9.74964918e+09, 1.00000000e+10])},
             scoring='neg_mean_absolute_error')

In [78]:
best_para = gsc.best_params_
best_para

{'alpha': 0.11942000281335322}

In [79]:
gsc.score(xtrain, ytrain)

-3.2743179775820805

In [80]:
gsc.score(xtest, ytest)

-3.299958903717942

In [81]:
gsc_pred = gsc.predict(xtest)
gsc_pred

array([28.48516571, 34.37762387, 18.16949796, 24.93055158, 18.54958044,
       23.8285386 , 18.02810038, 15.21289602, 22.22218117, 20.99659577,
       23.95831277, 19.53081636, -5.11659126, 22.60646536, 19.36588915,
       25.59119857, 19.03225738,  5.29182302, 38.90428974, 17.51002728,
       26.12519649, 28.48077586, 12.17850626, 24.45661222, 17.54188113,
       15.03849749, 23.18496328, 15.17131931, 22.17632034, 19.62601854,
       21.74655359, 25.27001567, 25.85871057, 17.35036965, 16.05229581,
       18.10806918, 31.68073212, 19.91512642, 23.48981869, 24.59140584,
       14.27307328, 30.07808641, 40.12689063, 18.13522455, 27.27041545,
       16.46890717, 14.6971395 , 25.89089865, 19.65333235, 30.56586975,
       21.97086322, 33.15862591, 16.80077315, 26.87851999, 38.43647559,
       22.17947057, 18.62173906, 30.63517412, 25.0688473 , 13.68000299,
       20.37430866, 29.43991167, 30.38610838, 16.15704714, 22.88435344,
       16.3789056 , 20.1387762 , 25.58620523, 29.05554542, 11.82580173,
       20.15530133, 26.8669663 , 11.12528597, 17.05213245, 24.14791947,
        6.63387194, 22.05379647, 38.83437453, 18.48673402, 12.12322537,
       21.6686153 , 12.19005321, 21.37030614,  8.81039192, 23.10595353,
       31.18700023, 19.21686943, 25.57063959, 27.36241202, 21.1808453 ,
       25.16211358,  5.89158877, 21.3067586 , 17.43112578, 11.27496487,
       21.96297299, 23.79962992, -0.5953067 , 14.26691015, 15.9895076 ,
       22.02474844, 25.04896223])

In [82]:
r2_score(ytest, gsc_pred)

0.6407716824635512