In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("Customer-Churn-Prediction.csv")
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [3]:
df.shape

(7043, 21)

In [4]:
df.isna().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [5]:
df.duplicated().sum()

0

In [6]:
from sklearn.preprocessing import LabelEncoder
from pandas.api.types import is_numeric_dtype
le = LabelEncoder()
for col in df.columns:
    if col == 'Churn':
        continue
    if is_numeric_dtype (df[col]):
        continue
    else:
        df[col] = le.fit_transform(df[col])

In [7]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,5375,0,0,1,0,1,0,1,0,0,...,0,0,0,0,0,1,2,29.85,2505,No
1,3962,1,0,0,0,34,1,0,0,2,...,2,0,0,0,1,0,3,56.95,1466,No
2,2564,1,0,0,0,2,1,0,0,2,...,0,0,0,0,0,1,3,53.85,157,Yes
3,5535,1,0,0,0,45,0,1,0,2,...,2,2,0,0,1,0,0,42.30,1400,No
4,6511,0,0,0,0,2,1,0,1,0,...,0,0,0,0,0,1,2,70.70,925,Yes

In [9]:
x = df.drop(['customerID','Churn'],axis=1)
y = df['Churn']

In [11]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2, random_state = 42)

In [12]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(xtrain,ytrain)

RandomForestClassifier()

In [13]:
rf.score(xtrain,ytrain)

0.9985800496982605

In [14]:
rf.score(xtest,ytest)

0.7955997161107168

In [15]:
#  After sampling

In [17]:
from imblearn.combine import SMOTETomek
from imblearn.over_sampling import SMOTE

sm = SMOTETomek(smote=SMOTE(k_neighbors=2), random_state=42)

In [19]:
newx,newy = sm.fit_resample(x,y)

In [20]:
x_train, x_test, y_train,y_test = train_test_split(newx,newy, test_size=0.2, random_state=42)

In [21]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [22]:
rf.score(x_train,y_train)

0.9982271748765353

In [23]:
rf.score(x_test,y_test)

0.8556962025316456

In [26]:
y.value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [27]:
newy.value_counts()

Churn
No     4936
Yes    4936
Name: count, dtype: int64

In [28]:
# Oversampling

In [30]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler()
new_x, new_y = ros.fit_resample(x,y)

In [31]:
y.value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [32]:
new_y.value_counts()

Churn
No     5174
Yes    5174
Name: count, dtype: int64

In [38]:
xtrain1, xtest1, ytrain1,ytest1  = train_test_split(new_x, new_y, test_size = 0.2, random_state=42)
rf.fit(xtrain1,ytrain1)

RandomForestClassifier()

In [39]:
rf.score(xtrain1,ytrain1)

0.9980671659821213

In [40]:
rf.score(xtest1,ytest1)

0.8951690821256039

In [ ]:
# Undersampling

In [34]:
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler()
newx1, newy1 = rus.fit_resample(x,y)

In [35]:

y.value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [36]:
newy1.value_counts()

Churn
No     1869
Yes    1869
Name: count, dtype: int64

In [43]:
xtrain2, xtest2,ytrain2,ytest2 = train_test_split(newx1,newy1, test_size=0.2, random_state = 42)

In [44]:
rf.fit(xtrain2,ytrain2)

RandomForestClassifier()

In [45]:
rf.score(xtrain2,ytrain2)

0.9983277591973244

In [46]:
rf.score(xtest2,ytest2)

0.7446524064171123

In [47]:
# k fold

In [48]:
from sklearn.model_selection import KFold, cross_val_score
kfold = KFold(n_splits=5, shuffle=True)

In [49]:
model = cross_val_score(rf,x,y,cv=kfold)

In [50]:
model.mean()

0.7918497765984902

In [51]:
model

array([0.79347055, 0.78495387, 0.79914833, 0.78338068, 0.79829545])

In [52]:
# SMOTE

In [53]:
from imblearn.combine import SMOTETomek
from imblearn.over_sampling import SMOTE
sm = SMOTETomek(smote=SMOTE(k_neighbors=2),random_state = 100)
newx2,newy2 = sm.fit_resample(x,y)

In [56]:
model2 = cross_val_score(rf,newx2,newy2,cv=kfold)

In [58]:
model2

array([0.85145482, 0.86830015, 0.86874362, 0.86976507, 0.86159346])

In [59]:
model2.mean()

0.8639714244150124

In [60]:
from sklearn.model_selection import KFold,cross_val_score
kfold = KFold(n_splits=2,shuffle=True)

In [61]:
rf = RandomForestClassifier()
cross_val_score(rf,x,y,cv=kfold)

array([0.78733674, 0.79664868])